GET https://nodejs-todolist-2i7kdhivr-calanfive.vercel.app

###

GET http://localhost:3000/add/:nom

###

GET http://localhost:3000/get-all/


###
PUT http://localhost:3000/update/1/1

###
PUT http://localhost:3000/remove/1

###
GET  http://localhost:3000/remove-all

